<?php $h=ag_section('hero','home'); get_header(); ?>
<section class="trade-hero" aria-labelledby="trade-title" data-trade-hero>
<img class="trade-poster" src="<?php echo esc_url(ag_media_url($h['image'])); ?>" alt="<?php echo esc_attr($h['alt']); ?>" width="1920" height="1080" fetchpriority="high">
<video class="trade-video" data-hero-video muted loop playsinline preload="none" aria-hidden="true" tabindex="-1" poster="<?php echo esc_url(ag_media_url($h['image'])); ?>" data-av1="<?php echo esc_url(ag_media_url($h['video']?'':$h['av1'])); ?>" data-h264="<?php echo esc_url(ag_media_url($h['video']?:$h['h264'])); ?>"></video>
<div class="trade-shade" aria-hidden="true"></div><div class="wrap trade-content"><span class="eyebrow trade-eyebrow"><?php ag_text($h,'eyebrow'); ?></span><h1 id="trade-title"><?php ag_text($h,'line1'); ?><br><?php ag_text($h,'line2'); ?></h1><p><?php ag_text($h,'body'); ?></p><div class="actions"><a class="button trade-button" href="<?php echo esc_url(ag_link($h['link'])); ?>"><?php ag_text($h,'label'); ?> <span aria-hidden="true">←</span></a><a class="button ghost trade-button" href="#import-categories"><?php ag_text($h,'secondary_label'); ?></a></div></div>
<div class="wrap trade-bottom"><div class="trade-capabilities"><span><?php ag_text($h,'capability_1'); ?></span><i aria-hidden="true"></i><span><?php ag_text($h,'capability_2'); ?></span><i aria-hidden="true"></i><span><?php ag_text($h,'capability_3'); ?></span></div></div><a class="trade-scroll" href="#import-categories" aria-label="مشاهده حوزه‌های واردات"><span aria-hidden="true">↓</span></a>
</section>
<div class="wrap category-strip"><strong><?php ag_text($h,'strip_title'); ?></strong><?php foreach(vatan_categories() as $s=>$c) echo '<a href="'.esc_url(vatan_url('products/'.$s.'/')).'">'.esc_html($c[0]).'</a>'; ?></div>
<?php get_template_part('template-parts/product-revolver'); get_template_part('template-parts/cooperation-gallery'); get_template_part('template-parts/home-story'); get_footer(); ?>
