<?php
get_header();the_post();$slug=get_post_field('post_name',get_the_ID());$custom=trim(get_the_content());
if($slug==='products'){
 vatan_intro('محصولات وطن','پنج گروه محصول؛ برای انتخاب، مشاوره و استعلام شرایط تامین.'); ?>
 <section class="section"><div class="wrap"><div class="category-grid"><?php $i=0;foreach(vatan_categories() as $s=>$c){$i++; ?><a class="category-card <?php if($s==='coffee')echo 'main'; ?>" href="<?php echo esc_url(vatan_url('products/'.$s.'/')); ?>"><?php if($s==='coffee'){ ?><img src="<?php echo esc_url(vatan_asset('coffee-detail.webp')); ?>" alt="فنجان و دانه‌های قهوه" loading="lazy"><?php } ?><span class="number">0<?php echo (int)$i; ?></span><div class="card-copy"><h3><?php echo esc_html($c[0]); ?></h3><p><?php echo esc_html($c[2]); ?></p></div></a><?php } ?></div></div></section>
 <section class="section"><div class="wrap"><span class="eyebrow">برای نیاز کسب‌وکار شما</span><h2>گفتگو درباره تامین عمده</h2><p>گروه محصول، مقدار تقریبی و شهر مقصد را در درخواست ذکر کنید.</p><a class="button" href="<?php echo esc_url(vatan_url('inquiry/')); ?>">ثبت استعلام</a></div></section><?php
}elseif(in_array($slug,['solutions','b2b-supply'],true)){
 vatan_intro($slug==='solutions'?'همکاری تجاری':'تامین سازمانی و عمده','برای کافه، هتل، رستوران، فروشگاه، سازمان و عمده‌فروش.'); ?>
 <section class="section"><div class="wrap split"><div class="statement"><span class="eyebrow">از نیاز تا پیشنهاد</span><h2>هر کسب‌وکار،<br><span class="gold">انتخاب خودش را دارد.</span></h2><p>انتخاب محصول به نوع مصرف، مقدار سفارش و شرایط کسب‌وکار شما بستگی دارد. درخواست را ثبت کنید تا امکان تامین و شرایط همکاری بررسی شود.</p><a class="button" href="<?php echo esc_url(vatan_url('inquiry/')); ?>">درخواست تماس کارشناس</a></div><div><img class="wide-photo" src="<?php echo esc_url(vatan_asset('ingredients.webp')); ?>" alt="گروه‌های محصولات غذایی" loading="lazy"></div></div></section>
 <section class="section"><div class="wrap"><div class="section-head"><h2>همکاری متناسب با کسب‌وکار شما</h2></div><div class="content-grid"><?php foreach(['کافه، هتل و رستوران'=>'نوع مصرف، مقدار موردنیاز و شیوه سفارش را با ما در میان بگذارید.','فروشگاه و عمده‌فروش'=>'گروه کالا، حجم تقریبی و شهر مقصد را در استعلام ذکر کنید.','سازمان و مجموعه'=>'نیاز مجموعه و اطلاعات مسیول هماهنگی را برای بررسی پیشنهاد ثبت کنید.'] as $t=>$d)echo '<div class="panel"><h3>'.esc_html($t).'</h3><p>'.esc_html($d).'</p></div>'; ?></div></div></section>
 <section class="section"><div class="wrap"><span class="eyebrow">چهار قدم برای شروع</span><div class="process"><div class="process-item"><b>01</b><h3>تعریف نیاز</h3><p>محصول، مقدار تقریبی و زمان موردنظر را مشخص کنید.</p></div><div class="process-item"><b>02</b><h3>ثبت اطلاعات</h3><p>درخواست و شماره تماس را در فرم وارد کنید.</p></div><div class="process-item"><b>03</b><h3>بررسی شرایط</h3><p>امکان تامین و جزییات موردنیاز بررسی می‌شود.</p></div><div class="process-item"><b>04</b><h3>توافق و هماهنگی</h3><p>شرایط نهایی با توافق شما مشخص می‌شود.</p></div></div></div></section><?php
}elseif($slug==='about'){
 vatan_intro('ارمغان تجارت وطن','وطن، نام تجاری شرکت ارمغان تجارت وطن است.'); ?>
 <section class="section"><div class="wrap split"><div class="statement"><span class="eyebrow">تامین و تجارت محصولات غذایی</span><h2>حرفه‌ای در انتخاب.<br><span class="gold">نزدیک در همکاری.</span></h2><p>فعالیت وطن بر قهوه و گروه‌های برنج، خشکبار، ادویه و حبوبات متمرکز است. این سایت مسیر شناخت محصولات، گفتگوی تجاری و ثبت درخواست همکاری را در اختیار شما می‌گذارد.</p><p>برای بررسی هر سفارش، اطلاعات محصول و شرایط همکاری در گفتگو با شما مشخص می‌شود.</p></div><img class="wide-photo" src="<?php echo esc_url(vatan_asset('coffee-hero.webp')); ?>" alt="فضای تیره و طلایی قهوه" loading="lazy"></div></section>
 <section class="section"><div class="wrap"><div class="content-grid"><div class="panel"><span class="eyebrow">۰۱</span><h3>انتخاب روشن</h3><p>پرسش درباره مشخصات محصول و نیاز مصرف، نقطه شروع انتخاب است.</p></div><div class="panel"><span class="eyebrow">۰۲</span><h3>گفتگوی مستقیم</h3><p>از فرم استعلام یا شماره دفتر، درخواست خود را با وطن در میان بگذارید.</p></div><div class="panel"><span class="eyebrow">۰۳</span><h3>همکاری مشخص</h3><p>موجودی، مقدار و شرایط سفارش پیش از توافق نهایی بررسی می‌شود.</p></div></div><div class="actions"><a class="button" href="<?php echo esc_url(vatan_url('inquiry/')); ?>">شروع گفتگو</a></div></div></section><?php
}elseif($slug==='contact'){
 vatan_intro('تماس با وطن','برای گفتگو درباره محصولات و همکاری تجاری، با ما در تماس باشید.'); ?>
 <section class="section"><div class="wrap split"><div><span class="eyebrow">شماره دفتر</span><a class="phone-large" href="tel:<?php echo esc_attr(vatan_option('phone','02191028166')); ?>"><?php echo esc_html(vatan_option('phone','02191028166')); ?></a><h2 style="font-size:1.5rem;margin-top:35px">نشانی دفتر</h2><p><?php echo esc_html(vatan_option('address','تهران، سهروردی شمالی، کوچه زمانی، پلاک ۱۱، ساختمان ایلیا، طبقه ۳، واحد ۹')); ?></p><div class="actions"><a class="button" href="<?php echo esc_url(vatan_url('inquiry/')); ?>">ثبت درخواست تماس</a><a class="button ghost" href="https://www.google.com/maps/dir/?api=1&destination=35.7294807434082,51.436744689941406" target="_blank" rel="noopener noreferrer">مسیریابی</a></div><?php $wa=preg_replace('/\D/','',vatan_option('whatsapp'));if($wa){ ?><div class="actions"><a class="text-link" href="<?php echo esc_url('https://wa.me/'.$wa.'?text='.rawurlencode('سلام، برای مشاوره و استعلام از سایت وطن پیام می‌دهم.')); ?>" target="_blank" rel="noopener noreferrer">گفتگو در واتس‌اپ</a></div><?php } ?></div><div class="panel"><h3>موقعیت دفتر</h3><p>تهران، سهروردی شمالی</p><button class="button ghost" type="button" data-map-load="https://www.openstreetmap.org/export/embed.html?bbox=51.4277%2C35.7242%2C51.4457%2C35.7347&amp;layer=mapnik&amp;marker=35.7294807434082%2C51.436744689941406">نمایش نقشه</button><p class="form-note">نقشه پس از انتخاب شما از اوپن‌استریت‌مپ بارگذاری می‌شود.</p></div></div></section><?php
}elseif($slug==='inquiry'){
 vatan_intro('درخواست همکاری و استعلام','از نیازتان بگویید؛ اطلاعات تماس را برای پاسخ به همین درخواست استفاده می‌کنیم.'); ?>
 <section class="section"><div class="wrap form-layout"><div><?php if(function_exists('vatan_inquiry_form'))echo vatan_inquiry_form();else echo '<p>فرم موقتاً در دسترس نیست. برای ثبت درخواست با دفتر تماس بگیرید.</p>'; ?></div><aside class="form-side"><span class="eyebrow">همکاری با وطن</span><h2>یک درخواست مشخص،<br>گفتگویی دقیق‌تر.</h2><p>برای بررسی بهتر، نام محصول، مقدار تقریبی و شهر خود را مشخص کنید. اگر هنوز انتخاب نکرده‌اید، گروه محصول را انتخاب کنید و در توضیحات از نیازتان بگویید.</p><a class="phone-large" style="font-size:1.8rem" href="tel:<?php echo esc_attr(vatan_option('phone','02191028166')); ?>"><?php echo esc_html(vatan_option('phone','02191028166')); ?></a><p class="form-note">اگر ثبت فرم با مشکل روبه‌رو شد، می‌توانید تلفنی درخواست خود را مطرح کنید.</p><?php $wa=preg_replace('/\D/','',vatan_option('whatsapp'));if($wa){ ?><a class="button ghost" href="<?php echo esc_url('https://wa.me/'.$wa.'?text='.rawurlencode('سلام، برای استعلام محصولات وطن پیام می‌دهم.')); ?>" target="_blank" rel="noopener noreferrer">گفتگو در واتس‌اپ</a><?php } ?></aside></div></section><?php
}elseif($slug==='thank-you'){
 $ref=isset($_GET['reference'])?sanitize_text_field(wp_unslash($_GET['reference'])):'';$matches=preg_match('/^VAT-[A-Z0-9]{10}$/D',$ref)?get_posts(['post_type'=>'vatan_lead','post_status'=>'private','posts_per_page'=>1,'meta_key'=>'_vatan_reference','meta_value'=>$ref,'fields'=>'ids']):[];
 if($matches){vatan_intro('درخواست شما ثبت شد.','اطلاعات شما ذخیره شد و برای بررسی در اختیار مسیول پیگیری قرار گرفت.'); ?><section class="section"><div class="wrap"><div class="empty"><span class="eyebrow">کد پیگیری درخواست</span><h2 dir="ltr" class="gold"><?php echo esc_html($ref); ?></h2><p>این کد را نگه دارید. برای پیگیری تلفنی، کد را به مسیول شرکت اعلام کنید. ثبت درخواست، تایید موجودی یا قبول سفارش نیست.</p><div class="actions"><a class="button" href="tel:<?php echo esc_attr(vatan_option('phone','02191028166')); ?>">تماس با وطن</a><a class="button ghost" href="<?php echo esc_url(vatan_url('products/')); ?>">بازگشت به محصولات</a></div></div></div></section><?php }else{vatan_intro('ثبت درخواست','برای ثبت و دریافت کد پیگیری، فرم استعلام را تکمیل کنید.'); ?><section class="section"><div class="wrap"><a class="button" href="<?php echo esc_url(vatan_url('inquiry/')); ?>">ورود به فرم استعلام</a></div></section><?php }
}elseif($slug==='media'){
 vatan_intro('رسانه وطن','گفتگوها و محتوای صوتی و تصویری درباره دنیای قهوه و محصولات غذایی.');$q=new WP_Query(['post_type'=>'vatan_episode','post_status'=>'publish','posts_per_page'=>9,'paged'=>max(1,get_query_var('paged'))]); ?><section class="section"><div class="wrap"><?php if($q->have_posts()){ ?><div class="content-grid"><?php while($q->have_posts()){$q->the_post(); ?><article class="product-card"><?php if(has_post_thumbnail())the_post_thumbnail('large',['class'=>'product-image']); ?><span class="eyebrow">رسانه / <?php echo esc_html(get_post_meta(get_the_ID(),'_vatan_duration',true)); ?></span><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><p><?php echo esc_html(get_the_excerpt()); ?></p><a class="text-link" href="<?php the_permalink(); ?>">مشاهده و شنیدن</a></article><?php } ?></div><?php echo paginate_links(['total'=>$q->max_num_pages]);wp_reset_postdata();}else{vatan_empty('هنوز اپیزودی منتشر نشده است.','محتوای صوتی و تصویری وطن پس از انتشار در این بخش قرار می‌گیرد. در این فاصله می‌توانید درباره محصولات با ما گفتگو کنید.');} ?></div></section><?php
}elseif($slug==='faq'){
 vatan_intro('پرسش‌های متداول','پاسخ به پرسش‌های مربوط به سایت و ثبت درخواست.');$faqs=['چطور درباره محصولات استعلام بگیرم؟'=>'گروه محصول را انتخاب کنید و از دکمه استعلام وارد فرم شوید. نام، موبایل، شهر و نوع مشتری را وارد کنید. پس از ثبت موفق، کد پیگیری نمایش داده می‌شود.','آیا در سایت خرید و پرداخت آنلاین انجام می‌شود؟'=>'خیر. سایت برای معرفی محصولات، مشاوره و ثبت درخواست همکاری است. شرایط سفارش در گفتگو با شرکت مشخص می‌شود.','اگر محصول دقیق را هنوز انتخاب نکرده‌ام چه کنم؟'=>'در فرم، گروه محصول را انتخاب کنید و در توضیحات از نیاز و نوع مصرف خود بگویید. واردکردن نام محصول اختیاری است.','ثبت فرم به معنی تایید موجودی است؟'=>'خیر. درخواست برای بررسی ثبت می‌شود؛ موجودی، مقدار و شرایط همکاری پیش از توافق نهایی مشخص خواهد شد.','در صورت مشکل در ثبت فرم چه کنم؟'=>'اگر ثبت موفق نباشد، پیام خطا را می‌بینید و اطلاعات فرم حفظ می‌شود. می‌توانید دوباره تلاش کنید یا با شماره دفتر تماس بگیرید.','چطور درخواست ثبت‌شده را پیگیری کنم؟'=>'کد پیگیری را نگه دارید و هنگام تماس با دفتر اعلام کنید.']; ?><section class="section"><div class="wrap faq"><?php foreach($faqs as $t=>$d)echo '<details><summary>'.esc_html($t).'</summary><p>'.esc_html($d).'</p></details>'; ?><div class="actions"><a class="button" href="<?php echo esc_url(vatan_url('inquiry/')); ?>">ثبت استعلام</a></div></div></section><?php
}elseif($slug==='privacy'){
 vatan_intro('حریم خصوصی','اطلاعات فرم برای رسیدگی به درخواست شما استفاده می‌شود.'); ?><section class="section"><div class="wrap editorial"><h2>اطلاعاتی که ثبت می‌کنید</h2><p>فرم استعلام شامل نام، موبایل، شهر، نوع مشتری و گروه محصول است. می‌توانید نام مجموعه، محصول، مقدار تقریبی، توضیحات و زمان ترجیحی تماس را هم ثبت کنید.</p><h2>هدف استفاده</h2><p>اطلاعات برای بررسی استعلام، تماس و پیگیری همکاری استفاده می‌شود. ثبت رضایت شما و زمان آن همراه درخواست نگهداری می‌شود.</p><h2>دسترسی به درخواست</h2><p>درخواست‌ها عمومی نیستند. مدیران مجاز سایت می‌توانند آن‌ها را برای رسیدگی مشاهده کنند. شماره موبایل و جزییات درخواست در صفحات عمومی سایت نمایش داده نمی‌شود.</p><h2>اصلاح یا حذف</h2><p>برای درخواست اصلاح یا حذف اطلاعات، با شماره دفتر تماس بگیرید و کد پیگیری خود را اعلام کنید. درخواست‌ها تا زمان حذف توسط مدیر در سامانه باقی می‌مانند.</p><h2>خدمات خارجی</h2><p>نقشه فقط پس از انتخاب شما از اوپن‌استریت‌مپ بارگذاری می‌شود. لینک مسیریابی شما را به گوگل مپ می‌برد. اگر کانال واتس‌اپ شرکت فعال شود، استفاده از آن تابع شرایط سرویس واتس‌اپ خواهد بود.</p><h2>ارتباط</h2><a class="text-link" href="tel:<?php echo esc_attr(vatan_option('phone','02191028166')); ?>"><?php echo esc_html(vatan_option('phone','02191028166')); ?></a></div></section><?php
}elseif($slug==='search'){
 vatan_intro('جستجو در وطن','محصول، مقاله یا موضوع موردنظر را پیدا کنید.');$term=isset($_GET['q'])?mb_substr(sanitize_text_field(wp_unslash($_GET['q'])),0,150):''; ?><section class="section"><div class="wrap"><form class="search-form" method="get" action="<?php echo esc_url(vatan_url('search/')); ?>"><label class="sr-only" for="search-q">عبارت جستجو</label><input class="search-input" type="search" id="search-q" name="q" value="<?php echo esc_attr($term); ?>" placeholder="جستجوی محصول یا موضوع" required maxlength="150"><button class="button" type="submit">جستجو</button></form><?php if($term){$q=new WP_Query(['s'=>$term,'post_type'=>['vatan_product','vatan_episode','post','page'],'post_status'=>'publish','posts_per_page'=>12,'paged'=>max(1,get_query_var('paged')),'post__not_in'=>array_filter([get_the_ID(),get_page_by_path('thank-you')->ID??0])]);if($q->have_posts()){while($q->have_posts()){$q->the_post();?><article class="result"><small><?php echo esc_html(get_post_type_object(get_post_type())->labels->singular_name); ?></small><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),30)); ?></p></article><?php }echo paginate_links(['total'=>$q->max_num_pages]);wp_reset_postdata();}else{echo '<div class="empty"><h2>نتیجه‌ای پیدا نشد.</h2><p>عبارت کوتاه‌تر یا نام گروه محصول را امتحان کنید.</p></div>';}} ?></div></section><?php
}else{vatan_intro(get_the_title()); ?><section class="section"><div class="wrap editorial"><?php the_content(); ?></div></section><?php }
if($custom&&in_array($slug,['products','about','contact','solutions','b2b-supply','media','faq','privacy'],true)){ ?><section class="section"><div class="wrap editorial"><?php the_content(); ?></div></section><?php }
get_footer();
