#!/usr/bin/env python3
"""Combine theme CSS in its verified cascade order. Source files remain editable."""
from pathlib import Path
import json,posixpath,re
root=Path(__file__).resolve().parent.parent;theme=root/'theme/vatan-authority';dest=theme/'assets'
base=['style.css','assets/video-hero.css','assets/home-story.css','assets/interior.css']
plans={'site-home.css':base+['assets/capabilities.css','assets/product-revolver.css','assets/cooperation-gallery.css'],'site-interior.css':base+['assets/art-direction.css','assets/capabilities.css'],'site-gallery.css':base+['assets/art-direction.css','assets/capabilities.css','assets/product-revolver.css','assets/cooperation-gallery.css']}
for name,files in plans.items():
 files=files+(['assets/page-opening.css'] if name!='site-home.css' else [])+['assets/brand-accent.css']+(['assets/authority-edition.css','assets/about-editorial.css','assets/approved-interiors.css'] if name!='site-home.css' else [])+['assets/shared-header.css']
 parts=[]
 for path in files:
  src=theme/path;css=src.read_text()
  def url(m):
   value=m.group(1).strip().strip('"\'')
   if value.startswith(('data:','http:','https:','#','/')):return m.group(0)
   target=posixpath.normpath(posixpath.join(posixpath.dirname(path),value));return 'url("'+posixpath.relpath(target,'assets')+'")'
  css=re.sub(r'url\(([^)]+)\)',url,css)
  css=re.sub(r'/\*.*?\*/','',css,flags=re.S);parts.append(re.sub(r'\s+',' ',css).strip())
 (dest/name).write_text('/* Generated by scripts/build-assets.py; edit the source stylesheets. */\n'+'\n'.join(parts)+'\n')
print('Built three CSS bundles in the original cascade order.')
